language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6-dev"
    - "pypy"

install:
    - pip install coverage

script:
    - |
      if [[ $(bc <<< "$TRAVIS_PYTHON_VERSION >= 3.3") -eq 1 ]]; then
         nosetests --with-doctest
      else
         nosetests --with-doctest -I '.*_3only.py$'
      fi

after_success:
    - |
      if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls; coveralls ; fi

notifications:
  email: false
